-- Bucket for the ORIGINAL document PDF (the one the customer reads and signs).
-- Generated by the CRM admin via Electron printToPDF using the existing
-- pdf_mallar template, uploaded with service_role at link creation time.
-- Customers download via public URL through their iframe.

INSERT INTO storage.buckets (id, name, public)
VALUES ('signing-pdfs', 'signing-pdfs', true)
ON CONFLICT (id) DO UPDATE SET public = EXCLUDED.public;

-- Public read so the customer's browser can fetch the PDF for display.
DROP POLICY IF EXISTS signing_pdfs_select ON storage.objects;
CREATE POLICY signing_pdfs_select ON storage.objects
  FOR SELECT
  TO anon, authenticated
  USING (bucket_id = 'signing-pdfs');

-- Writes are admin-only via service_role (no policies for anon/authenticated).
-- The CRM admin's IPC handler uploads with service_role bypass.

-- Track the document PDF URL on each link.
ALTER TABLE signatur_lankar
  ADD COLUMN IF NOT EXISTS document_pdf_url TEXT;
